version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 422299502737.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t node-hello:latest .
      - docker tag node-hello:latest 422299502737.dkr.ecr.eu-central-1.amazonaws.com/node-hello:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 422299502737.dkr.ecr.eu-central-1.amazonaws.com/node-hello:latest 
